---
event:
  id: 1
  url: http://connpass.com/event/33284/
  thema:
    title: Mackerelをサーバ監視/管理"以外"に使う
    description: |-
      Mackerelの変な使い方の事例を自慢してみましょう。
      もちろん、正しい使い方の紹介も大歓迎です！
  venue:
    name: 株式会社エウレカ
    address: 東京都港区南青山2-27-25 (オリックス南青山ビル6F)
    url: http://eure.jp/about/#access_map
    capacity: 50
  date: 2016-06-14
  open_at: 19:00
  start_at: 19:30
  timetable:
    - type: announce
      minutes: 10
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: break
      minutes: 10
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: party
      minutes: 120
  sponsors: []
    # - name: ~
    #   url: ~
  party:
    venue: 会場
    fee: 2000