---
event:
  id: 2
  url: ~
  thema:
    title: XaaS meets Mackerel
    description: |-
      AWS/GCP/AzureなどのXaaSの採用事例が増えてきているなかで知見を交換したいというニーズが高まっているかと思います。
      MackerelもAWS Integrationが提供されており、最近はAzure Integrationも提供されました。Mackerelと組み合わせた事例について気になっている方も多いのではないでしょうか。
      今回のMackerel User Groupでは、XaaSとMackerelにフォーカスしてカジュアルにLTなどをしつつそれを肴にざっくばらんに話ができる場にできるといいなと思っています。
      5分間なので話のネタづくりにという気持ちで気軽に話してみましょう！
  venue:
    name: CAMPFIRE, Inc.
    address: 東京都渋谷区渋谷2丁目22-3 (渋谷東口ビル5F)
    url: http://www.campfire.co.jp/about.html
    capacity: 60 # キツキツで100、余裕持って80
  date: 2017-08-23
  open_at: 19:00
  start_at: 19:30
  timetable:
    - type: announce
      minutes: 10
    - type: lt
      minutes: 5
      speaker: nil
      detail: nil
    - type: lt
      minutes: 5
      speaker: nil
      detail: nil
    - type: lt
      minutes: 5
      speaker: nil
      detail: nil
    - type: lt
      minutes: 5
      speaker: nil
      detail: nil
    - type: break
      minutes: 10
    - type: lt
      minutes: 5
      speaker: nil
      detail: nil
    - type: lt
      minutes: 5
      speaker: nil
      detail: nil
    - type: lt
      minutes: 5
      speaker: nil
      detail: nil
    - type: lt
      minutes: 5
      speaker: nil
      detail: nil
    - type: party
      minutes: 120
  party:
    venue: 会場
    fee: 3000
