---
event:
  id: 1
  url: http://mackerel-ug.connpass.com/event/33287/
  thema:
    title: Mackerelをサーバ監視/管理"以外"に使う
    description: |-
      Mackerelの変な使い方の事例を自慢してみましょう。
      もちろん、正しい使い方の紹介も大歓迎です！
  venue:
    name: 株式会社エウレカ
    address: 東京都港区南青山2-27-25 (オリックス南青山ビル6F)
    url: http://eure.jp/about/#access_map
    capacity: 50 # キツキツで100、余裕持って80
  date: 2016-06-14
  open_at: 19:00
  start_at: 19:30
  timetable:
    - type: announce
      minutes: 10
    - type: lt
      minutes: 5
      speaker: buty4649
      detail: Mackerel UGの説明
    - type: lt
      minutes: 5
      speaker: hoto17296
      detail: Mackerel でおうちハック
    - type: lt
      minutes: 5
      speaker: papix
      detail: Mackerelでpapixを監視する (仮)
    - type: lt
      minutes: 5
      speaker: a-know
      detail: 個人で Mackerel standard プランを使い倒したい話（仮）
    - type: break
      minutes: 10
    - type: lt
      minutes: 5
      speaker: karupanerura
      detail: go-check-pluginsに送ったpull-reqの紹介
    - type: lt
      minutes: 5
      speaker: sion_cojp
      detail: MackerelでGET WILD
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: lt
      minutes: 5
      speaker: undef
      detail: undef
    - type: party
      minutes: 120
  sponsors:
    - name: 株式会社はてな
      url: http://hatenacorp.jp/
    - name: 株式会社エウレカ
      url: http://eure.jp/
  party:
    venue: 会場
    fee: 0
